---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  aries-dogfood:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_dogfood.yml
        additional-parameters:
          b2g_update_channel: 'nightly-b2g44'
  flame-kk-ota:
    platforms:
      - b2g
    types:
      debug:
        task: tasks/builds/b2g_flame_kk_ota_debug.yml
        additional-parameters:
          b2g_update_channel: 'nightly-b2g44'
  nexus-4-kk-ota:
    platforms:
      - b2g
    types:
      debug:
        task: tasks/builds/b2g_nexus_4_kk_ota_debug.yml
        additional-parameters:
          b2g_update_channel: 'nightly-b2g44'
  nexus-5l-ota:
    platforms:
      - b2g
    types:
      debug:
        task: tasks/builds/b2g_nexus_5l_ota_debug.yml
        additional-parameters:
          b2g_update_channel: 'nightly-b2g44'

# Just needed for parser sake
tests: []
