---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux:
    platforms:
      - Linux
    types:
      debug:
        task: tasks/builds/dbg_linux32.yml
  linux64:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-st-an:
    platforms:
      - Linux64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_linux64_st-an.yml
  macosx64:
    platforms:
      - MacOSX64
    types:
      debug:
        task: tasks/builds/dbg_macosx64.yml
  macosx64-st-an:
    platforms:
      - MacOSX64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_macosx64_st-an.yml

tests:
  mochitest-webgl:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl.yml
