$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'nexus-4-kk-ota'
    build_type: 'debug'
task:
  workerType: balrog
  metadata:
    name: '[TC] B2G Nexus 4 KK OTA (userdebug)'
  scopes:
    - 'docker-worker:cache:build-nexus-4-kk-ota-debug'
    - 'docker-worker:cache:build-nexus-4-kk-ota-debug-objdir-gecko-{{project}}'
    - 'docker-worker:feature:balrogVPNProxy'

  payload:
    features:
      balrogVPNProxy: true
    cache:
      build-nexus-4-kk-ota-debug: /home/worker/workspace
      build-nexus-4-kk-ota-debug-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      VARIANT: userdebug
      B2G_DEBUG: 0
      TARGET: 'nexus-4-kk'
      DEBUG: 0
      B2G_UPDATE_CHANNEL: '{{b2g_update_channel}}'
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone-ota.sh $HOME/workspace
  extra:
    locations:
      img: 'private/build/nexus-4-kk.zip'
    treeherderEnv:
      - staging
    treeherder:
      symbol: B
      groupSymbol: Nexus-4-KK-OTA
      groupName:  Nexus 4 KitKat Device Image
      machine:
        platform: b2g-device-image
      collection:
        debug: true
