$inherits:
  from: 'tasks/builds/b2g_flame_kk_ota_base.yml'
  variables:
    build_name: 'flame-kk-ota'
    build_type: 'opt'
task:
  metadata:
    name: '[TC] B2G Flame KK OTA (user)'
  scopes:
    - 'docker-worker:cache:build-flame-kk-ota-user'
    - 'docker-worker:cache:build-flame-kk-ota-user-objdir-gecko-{{project}}'

  payload:
    cache:
      build-flame-kk-ota-user: /home/worker/workspace
      build-flame-kk-ota-user-objdir-gecko-{{project}}: /home/worker/objdir-gecko
    env:
      VARIANT: user
      MOZHARNESS_CONFIG: b2g/taskcluster-phone-fota.py
      B2G_UPDATE_CHANNEL: '{{b2g_update_channel}}'
  extra:
    treeherderEnv:
      - staging
    treeherder:
      symbol: B
      groupSymbol: Flame-KK-OTA
      groupName:  Flame KitKat Device Image
      machine:
        platform: b2g-device-image
