$inherits:
  from: 'tasks/build.yml'
  variables:
    build_product: 'firefox'
task:
  extra:
    locations:
      mozharness: 'public/build/mozharness.zip'
      test_packages: 'public/build/test_packages.json'
