$inherits:
  # inherit clobber since we want to use a different workspace cache
  from: 'tasks/builds/linux64_clobber.yml'
  variables:
    build_name: 'linux64-st-an'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] Linux64 Static Analysis Opt'
      description: 'Linux64 Static Analysis Opt'

  scopes:
    - 'docker-worker:cache:build-{{project}}-linux64-st-an-workspace'

  routes:
    - 'index.buildbot.branches.{{project}}.linux64-st-an'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux64-st-an'

  workerType: opt-linux64

  payload:
    cache:
      build-{{project}}-linux64-st-an-workspace: '/home/worker/workspace'
    env:
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      MOZHARNESS_CONFIG: 'builds/releng_sub_linux_configs/64_stat_and_opt.py balrog/production.py'
      DIST_UPLOADS: ''
      DIST_TARGET_UPLOADS: ''

  extra:
    treeherder:
      groupSymbol: "?"
      symbol: S
