---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_jobs.yml

# Flags specific to this branch
flags:
  post-build:
    - upload-symbols

builds:
  emulator-x86-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_l_opt.yml
  dolphin:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_opt.yml
  dolphin-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_eng.yml
  dolphin-512:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_512_opt.yml
  dolphin-512-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_dolphin_512_eng.yml
  android-api-11:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_11.yml
  android-partner-sample1:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_11_partner_sample1.yml
  linux:
    platforms:
      - Linux
    types:
      opt:
        task: tasks/builds/opt_linux32_clobber.yml
      debug:
        task: tasks/builds/dbg_linux32_clobber.yml
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64_clobber.yml
      debug:
        task: tasks/builds/dbg_linux64_clobber.yml
  linux64-st-an:
    platforms:
      - Linux64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_linux64_st-an_clobber.yml
  macosx64:
    platforms:
      - MacOSX64
    types:
      debug:
        task: tasks/builds/dbg_macosx64_clobber.yml
  macosx64-st-an:
    platforms:
      - MacOSX64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_macosx64_st-an_clobber.yml
  sm-plain:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_plain.yml
      debug:
       task: tasks/builds/sm_plaindebug.yml
  sm-arm-sim:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim.yml
  sm-arm-sim-osx:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_arm_sim_osx.yml
  sm-compacting:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_compacting.yml
  sm-generational:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_generational.yml
  sm-rootanalysis:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_rootanalysis.yml
  sm-warnaserr:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_warnaserr.yml
      debug:
        task: tasks/builds/sm_warnaserrdebug.yml

post-build:
  upload-symbols:
    allowed_build_tasks:
      - tasks/builds/opt_linux64.yml
      - tasks/builds/opt_linux64_st-an.yml
      - tasks/builds/dbg_linux64.yml
      - tasks/builds/android_api_11.yml
    task: tasks/post-builds/upload_symbols.yml

tests:
  marionette:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_marionette.yml
  marionette-webapi:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_marionette_webapi.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_l_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
  mochitest-webgl:
    allowed_build_tasks:
      tasks/builds/dbg_linux64_clobber.yml:
        task: tasks/tests/fx_linux64_mochitest_gl.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_l_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_x86_kk_opt.yml:
        task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
